#!/usr/bin/env bash
#
# s3seal installer
#
#   curl -fsSL https://raw.githubusercontent.com/mhbahmani/s3seal/master/install.sh | bash
#
# Asks which clients to protect and where to install. Press Enter to accept the
# defaults. Installs s3seal, moves official clients out of PATH when you agree,
# and runs "s3seal enable" for each protected client.

set -euo pipefail

DEFAULT_REPO="mhbahmani/s3seal"
DEFAULT_REF="master"
REPO="${S3SEAL_REPO:-$DEFAULT_REPO}"
REF="${S3SEAL_REF:-$DEFAULT_REF}"
RAW_URL="https://raw.githubusercontent.com/$REPO/$REF"

CONFIG_DIR="${S3SEAL_CONFIG_DIR:-$HOME/.config/s3seal}"

# Files to install. Keep in sync with scripts/update-checksum.sh.
FILES="bin/mc bin/aws bin/s3seal lib/common.sh lib/ini.sh lib/aws.sh lib/mc.sh"
ENTRIES="bin/mc bin/aws bin/s3seal"

# SHA-256 of each file at the default ref. Regenerated by
# scripts/update-checksum.sh; the test suite fails if it is stale.
CHECKSUMS="$(cat <<'SUMS'
339298bd0141b31e5eaebad07db019cfc55111bee470aff57c63edcb0976d309  bin/mc
97a92a50f6365665732674de22853329215d3dda1be4060cb38ea704d4908469  bin/aws
a815f77d3c3439939446365c98fd4f2e5c52b0c923dde65a4867f1fdfd3bf3ba  bin/s3seal
473b91689311488a3ec5b5eb60df98e4dbfddc06be50a43dd1e07dd38549d333  lib/common.sh
902dc7031554f646477c24687e7cd87d70e2820b9a9d087641da3e9b526339c5  lib/ini.sh
f2683e3fdd92606e411d77a02f77e6841728b80416428ec3b932d9e5225cc5ad  lib/aws.sh
047c9db9c2dfa4fc9e3fede5f2735b62d9cf5170d826120d4da8573976463b13  lib/mc.sh
SUMS
)"

if [[ -t 1 ]]; then
  B=$'\033[1m'; R=$'\033[0m'; Y=$'\033[33m'; G=$'\033[32m'; E=$'\033[31m'
else
  B=''; R=''; Y=''; G=''; E=''
fi

info() { printf '%s\n' "$*"; }
ok()   { printf '%s✓%s %s\n' "$G" "$R" "$*"; }
warn() { printf '%s!%s %s\n' "$Y" "$R" "$*"; }
fail() { printf '%s✗%s %s\n' "$E" "$R" "$*" >&2; exit 1; }

# Upgrades run through "s3seal upgrade" and never ask questions.
# S3SEAL_YES=1 accepts every default without asking, for scripted installs.
INTERACTIVE=0
if [[ -z "${S3SEAL_UPGRADE:-}" && -z "${S3SEAL_YES:-}" ]] && { : < /dev/tty; } 2>/dev/null; then
  INTERACTIVE=1
fi

# ask QUESTION DEFAULT(y|n): returns 0 for yes. Without a terminal, uses DEFAULT.
ask() {
  local reply=''
  if (( INTERACTIVE )); then
    read -r -p "$1 " reply < /dev/tty || true
  fi
  reply="${reply:-$2}"
  [[ "$reply" =~ ^[Yy] ]]
}

# ask_dir QUESTION DEFAULT: prints the chosen directory, with ~ expanded.
ask_dir() {
  local reply=''
  if (( INTERACTIVE )); then
    read -r -p "$1 [$2]: " reply < /dev/tty || true
  fi
  reply="${reply:-$2}"
  printf '%s' "${reply/#\~/$HOME}"
}

sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

sum_for() { printf '%s\n' "$CHECKSUMS" | awk -v f="$1" '$2 == f { print $1 }'; }

is_wrapper() { grep -q '^# s3seal:' "$1" 2>/dev/null; }

# On many Linux distributions "mc" is Midnight Commander, not MinIO's client.
is_minio_mc() { "$1" --version 2>/dev/null | grep -q 'RELEASE\.'; }

# Resolves symlinks, so links into our own install are recognised.
resolve_path() {
  local s="$1" t
  while [[ -L "$s" ]]; do
    t="$(readlink "$s")"
    [[ "$t" == /* ]] && s="$t" || s="$(dirname "$s")/$t"
  done
  printf '%s/%s' "$(cd "$(dirname "$s")" && pwd)" "$(basename "$s")"
}

# Prints the official client for NAME (a list of candidate names), skipping
# s3seal's own links. Prints nothing if there is none.
find_official() {
  local names="$1" name d c r
  if [[ -r "$CONFIG_DIR/${names%% *}-path" ]]; then
    c="$(head -n1 "$CONFIG_DIR/${names%% *}-path")"
    [[ -x "$c" ]] && { printf '%s' "$c"; return 0; }
  fi
  for name in $names; do
    for d in ${PATH//:/ }; do
      [[ -n "$d" ]] || continue
      c="$d/$name"
      [[ -f "$c" && -x "$c" ]] || continue
      r="$(resolve_path "$c")"
      [[ "$r" == */s3seal/bin/* ]] && continue
      if [[ "$name" == mc ]] && ! is_minio_mc "$c"; then
        warn "$c is not the MinIO client (Midnight Commander?); ignoring it" >&2
        continue
      fi
      printf '%s' "$c"
      return 0
    done
  done
  return 1
}

version_of() { sed -n 's/^VERSION="\(.*\)"$/\1/p' "$1" 2>/dev/null | head -n1; }

client_label() {
  case "$1" in
    mc) printf 'mc    the MinIO client' ;;
    aws) printf 'aws   the AWS CLI' ;;
  esac
}

# Checkbox menu over the names given. Up and down move, space toggles, Enter
# confirms. All start checked. Prints the chosen names on stdout.
checkbox_menu() {
  local -a names=("$@") checked=()
  local n=${#names[@]} i cur=0 key rest first=1 mark ptr
  for ((i = 0; i < n; i++)); do checked[i]=1; done
  printf 'Select the clients to protect (arrows move, space toggles, Enter confirms):\n' >&2
  while true; do
    if (( ! first )); then printf '\033[%dA' "$n" >&2; fi
    first=0
    for ((i = 0; i < n; i++)); do
      mark=' '; ptr=' '
      if (( checked[i] )); then mark='x'; fi
      if (( i == cur )); then ptr='>'; fi
      printf '\033[2K %s [%s] %s\n' "$ptr" "$mark" "$(client_label "${names[i]}")" >&2
    done
    IFS= read -rsn1 key < /dev/tty || break
    if [[ "$key" == $'\e' ]]; then
      IFS= read -rsn2 rest < /dev/tty || true
      case "$rest" in
        '[A') if (( cur > 0 )); then cur=$((cur - 1)); else cur=$((n - 1)); fi ;;
        '[B') cur=$(((cur + 1) % n)) ;;
      esac
    elif [[ "$key" == ' ' ]]; then
      checked[cur]=$((1 - checked[cur]))
    elif [[ -z "$key" ]]; then
      break
    fi
  done
  local out=''
  for ((i = 0; i < n; i++)); do
    if (( checked[i] )); then out+="${names[i]} "; fi
  done
  printf '%s' "$out"
}

# --- questions ---------------------------------------------------------------
printf '\n%ss3seal installer%s\n\n' "$B" "$R"
command -v gpg >/dev/null 2>&1 || fail "gpg is required"
command -v curl >/dev/null 2>&1 || fail "curl is required"

SEAL_MC=0 SEAL_AWS=0
if [[ -z "${S3SEAL_UPGRADE:-}" ]]; then
  # Only clients that are installed here can be protected.
  PRESENT=()
  if [[ -n "$(find_official "mc mcli" 2>/dev/null || true)" ]]; then PRESENT+=(mc); fi
  if [[ -n "$(find_official "aws" 2>/dev/null || true)" ]]; then PRESENT+=(aws); fi

  SELECTED=""
  if (( ${#PRESENT[@]} == 0 )); then
    info "No supported client was found on PATH (mc, aws). Install one and re-run the installer."
  elif (( INTERACTIVE )); then
    info ""
    SELECTED="$(checkbox_menu "${PRESENT[@]}")"
  else
    SELECTED="${PRESENT[*]}"
  fi
  case " $SELECTED " in *" mc "*) SEAL_MC=1 ;; esac
  case " $SELECTED " in *" aws "*) SEAL_AWS=1 ;; esac
  info ""
fi

if [[ -n "${S3SEAL_SHARE_DIR:-}" ]]; then
  SHARE_DIR="$S3SEAL_SHARE_DIR"
else
  SHARE_DIR="$(ask_dir "Install s3seal to" "$HOME/.local/share/s3seal")"
fi
if [[ -n "${S3SEAL_INSTALL_DIR:-}" ]]; then
  BIN_DIR="$S3SEAL_INSTALL_DIR"
else
  BIN_DIR="$(ask_dir "Put the commands in" "$HOME/.local/bin")"
fi
LIBEXEC_DIR="${S3SEAL_LIBEXEC_DIR:-}"   # asked later, only if an official client must move

# --- download and verify -----------------------------------------------------
info ""
stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT
mkdir -p "$stage/bin" "$stage/lib"

script_dir=""
if [[ -n "${BASH_SOURCE[0]:-}" && -f "${BASH_SOURCE[0]}" ]]; then
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

if [[ -n "$script_dir" && -f "$script_dir/bin/mc" && -f "$script_dir/lib/common.sh" ]]; then
  info "Copying s3seal from this checkout..."
  for f in $FILES; do cp "$script_dir/$f" "$stage/$f"; done
else
  info "Downloading s3seal from $REPO@$REF..."
  verify=0
  [[ "$REPO" == "$DEFAULT_REPO" && "$REF" == "$DEFAULT_REF" ]] && verify=1
  for f in $FILES; do
    curl -fsSL "$RAW_URL/$f" -o "$stage/$f" || fail "download failed: $RAW_URL/$f"
    info "  $f"
  done
  if (( verify )); then
    info "Checking checksums..."
    for f in $FILES; do
      expected="$(sum_for "$f")"
      actual="$(sha256 "$stage/$f")"
      [[ -n "$expected" && "$actual" == "$expected" ]] \
        || fail "checksum mismatch for $f (expected ${expected:-none}, got $actual). Refusing to install."
    done
    ok "all files match their checksums"
  else
    warn "not verified: only the default ref has checksums"
  fi
fi

for f in $ENTRIES; do
  head -n1 "$stage/$f" | grep -q '^#!' || fail "$f does not look like a script"
  grep -q '^# s3seal:' "$stage/$f" || fail "$f is not an s3seal file"
done
for f in $FILES; do
  bash -n "$stage/$f" || fail "$f failed a syntax check; refusing to install"
done

# --- install -----------------------------------------------------------------
installed_version=""
[[ -f "$SHARE_DIR/bin/s3seal" ]] && installed_version="$(version_of "$SHARE_DIR/bin/s3seal")"
new_version="$(version_of "$stage/bin/s3seal")"

changed=()
for f in $FILES; do
  cmp -s "$stage/$f" "$SHARE_DIR/$f" || changed+=("$f")
done

if [[ -z "$installed_version" ]]; then
  state=fresh
elif (( ${#changed[@]} == 0 )); then
  state=same
elif [[ "$installed_version" == "$new_version" ]]; then
  state=refresh
else
  state=upgrade
fi

case "$state" in
  fresh)   info "Installing s3seal $new_version." ;;
  same)    ok "s3seal $new_version is already installed and up to date." ;;
  refresh) info "s3seal $new_version is already installed. Refreshing ${#changed[@]} changed file(s)." ;;
  upgrade) info "Upgrading s3seal $installed_version -> $new_version." ;;
esac

mkdir -p "$SHARE_DIR/bin" "$SHARE_DIR/lib" "$BIN_DIR"
if [[ "$state" != same ]]; then
  for f in "${changed[@]}"; do
    case "$f" in
      lib/*) mode=0644 ;;
      *) mode=0755 ;;
    esac
    # Write beside the target and rename over it: a running s3seal keeps its old
    # file, so an upgrade started from s3seal itself cannot corrupt the process.
    install -m "$mode" "$stage/$f" "$SHARE_DIR/$f.new"
    mv -f "$SHARE_DIR/$f.new" "$SHARE_DIR/$f"
  done
  ok "installed s3seal $new_version into $SHARE_DIR"
fi
printf '%s %s\n' "$REPO" "$REF" > "$SHARE_DIR/source"

# Replaces a symlink or an older regular-file wrapper; refuses anything else.
link_command() {
  local target="$BIN_DIR/$1"
  if [[ -L "$target" && "$(readlink "$target")" == "$SHARE_DIR/bin/$1" ]]; then
    return 0
  fi
  if [[ -e "$target" || -L "$target" ]]; then
    if [[ -L "$target" ]] || is_wrapper "$target"; then
      rm -f "$target"
    else
      fail "$target exists and is not s3seal; move it aside and re-run"
    fi
  fi
  ln -s "$SHARE_DIR/bin/$1" "$target"
}
link_command s3seal
ok "linked s3seal into $BIN_DIR"

# Name of the user owning PATH (GNU and BSD stat differ).
owner_of() { stat -c %U "$1" 2>/dev/null || stat -f %Su "$1"; }

# Moves FROM to TO. On failure, explains which part of the permissions blocks
# it, and prints the command that does it with sudo.
move_client() {  # FROM TO
  local from="$1" to="$2" src_dir dst_dir owner
  src_dir="$(dirname "$from")"
  dst_dir="$(dirname "$to")"
  if mkdir -p "$dst_dir" 2>/dev/null && mv -f "$from" "$to" 2>/dev/null; then
    ok "  moved to $to"
    return 0
  fi
  owner="$(owner_of "$from")"
  warn "  could not move $from to $to"
  info "    running as user: $(id -un)"
  if [[ ! -w "$src_dir" ]]; then
    info "    $src_dir is not writable by $(id -un) (owned by $(owner_of "$src_dir"))"
  fi
  if ! mkdir -p "$dst_dir" 2>/dev/null; then
    info "    $dst_dir cannot be created by $(id -un)"
  elif [[ ! -w "$dst_dir" ]]; then
    info "    $dst_dir is not writable by $(id -un)"
  fi
  if [[ "$owner" != "$(id -un)" ]]; then
    info "    $from is owned by $owner"
  fi
  info "  Moving it needs root. Run this command yourself:"
  info "      sudo mv $from $to"
  return 1
}

# --- protected clients ------------------------------------------------------
# Moves an official client out of PATH (with consent) and records where it is,
# then lets "s3seal enable" take over the name.
setup_client() {  # NAME CANDIDATES
  local tool="$1" found new
  found="$(find_official "$2")" || true
  if [[ -z "$found" ]]; then
    warn "$tool: no official client found on PATH. Install it, then run: $SHARE_DIR/bin/s3seal enable $tool"
    return 0
  fi
  info "$tool: found the official client at $found"

  local here; here="$(dirname "$found")"
  if [[ "$here" != "$HOME/.local/libexec" && ( -z "$LIBEXEC_DIR" || "$here" != "$LIBEXEC_DIR" ) ]]; then
    if (( INTERACTIVE )) && ask "  Move it out of PATH so s3seal can use the name $tool? [Y/n]:" y; then
      if [[ -z "$LIBEXEC_DIR" ]]; then
        LIBEXEC_DIR="$(ask_dir "  Keep it in" "$HOME/.local/libexec")"
      fi
      new="$LIBEXEC_DIR/$tool"
      if move_client "$found" "$new"; then
        found="$new"
      elif (( INTERACTIVE )); then
        printf '  Run the command above in another terminal, then press Enter to continue.\n' >&2
        read -r -p '  ' _ < /dev/tty || true
        if [[ -f "$new" && ! -e "$found" ]]; then
          ok "  moved to $new"
          found="$new"
        else
          warn "  $found was not moved; continuing with its current location"
        fi
      fi
    else
      info "  left in place; $BIN_DIR must come before its directory on PATH."
    fi
  fi

  mkdir -p "$CONFIG_DIR"
  printf '%s\n' "$found" > "$CONFIG_DIR/$tool-path"
  S3SEAL_INSTALL_DIR="$BIN_DIR" "$SHARE_DIR/bin/s3seal" enable "$tool" \
    || warn "could not enable $tool; run: s3seal enable $tool"
}

if [[ -z "${S3SEAL_UPGRADE:-}" ]]; then
  if (( SEAL_MC )); then info ""; setup_client mc "mc mcli"; fi
  if (( SEAL_AWS )); then info ""; setup_client aws "aws"; fi
fi

# --- GPG recipient -----------------------------------------------------------
if [[ -z "${S3SEAL_UPGRADE:-}" && ! -s "$CONFIG_DIR/recipient" && -z "${S3SEAL_GPG_RECIPIENT:-}" ]]; then
  if (( INTERACTIVE )); then
    info ""
    rcpt=''
    read -r -p "GPG key for encrypting credentials (email or key id, Enter to set later): " rcpt < /dev/tty || true
    if [[ -n "$rcpt" ]]; then
      mkdir -p "$CONFIG_DIR"
      printf '%s\n' "$rcpt" > "$CONFIG_DIR/recipient"
      ok "saved the GPG recipient to $CONFIG_DIR/recipient"
    fi
  fi
  if [[ ! -s "$CONFIG_DIR/recipient" && -z "${S3SEAL_GPG_RECIPIENT:-}" ]]; then
    warn "no GPG recipient yet. Set one before storing credentials:"
    info "    echo 'you@example.com' > $CONFIG_DIR/recipient"
  fi
fi

# --- summary -----------------------------------------------------------------
info ""
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) warn "$BIN_DIR is not on your PATH. Add this to your shell rc file and start a new shell:"
     info "    export PATH=\$PATH:$BIN_DIR" ;;
esac
info "Done. Check the state with: s3seal status"
