#!/usr/bin/env bash
#
# s3seal installer
#
#   curl -fsSL https://raw.githubusercontent.com/mhbahmani/s3seal/master/install.sh | bash
#
# Installs s3seal into ~/.local/share/s3seal and links the mc wrapper and the
# s3seal command into ~/.local/bin. The AWS CLI is not touched until you run
# "s3seal enable aws".

set -euo pipefail

DEFAULT_REPO="mhbahmani/s3seal"
DEFAULT_REF="master"
REPO="${S3SEAL_REPO:-$DEFAULT_REPO}"
REF="${S3SEAL_REF:-$DEFAULT_REF}"
RAW_URL="https://raw.githubusercontent.com/$REPO/$REF"

INSTALL_DIR="${S3SEAL_INSTALL_DIR:-$HOME/.local/bin}"
SHARE_DIR="${S3SEAL_SHARE_DIR:-$HOME/.local/share/s3seal}"
LIBEXEC_DIR="${S3SEAL_LIBEXEC_DIR:-$HOME/.local/libexec}"
CONFIG_DIR="${S3SEAL_CONFIG_DIR:-$HOME/.config/s3seal}"

# Files to install. Keep in sync with scripts/update-checksum.sh.
FILES="mc aws s3seal lib/common.sh lib/ini.sh lib/aws.sh"
ENTRIES="mc aws s3seal"

# SHA-256 of each file at the default ref. Regenerated by
# scripts/update-checksum.sh; the test suite fails if it is stale.
CHECKSUMS="$(cat <<'SUMS'
89f121fafbf2c57523b0279693355ed185edc6c766cdb07e28f2eb32482dd218  mc
0e3b08bebc26b035f7a4a9e8ee3c509f08001f5f3f2b73d02d980102e9af5297  aws
da7fe28e0595c0eefa74b7adc02d52d304a6a0b6f70beddf863238239aaf1431  s3seal
ffd2d7d82692f5f4f5e6fe7f0f4b145fc948796ff8165f37695d43ae01fcbb35  lib/common.sh
902dc7031554f646477c24687e7cd87d70e2820b9a9d087641da3e9b526339c5  lib/ini.sh
c44c47d1080f58d90ae2b5c70676f0089882260367acbd0b1ff3d085eecffe47  lib/aws.sh
SUMS
)"

if [[ -t 1 ]]; then
  B=$'\033[1m'; R=$'\033[0m'; Y=$'\033[33m'; G=$'\033[32m'; E=$'\033[31m'
else
  B=''; R=''; Y=''; G=''; E=''
fi

info() { printf '%s\n' "$*"; }
ok()   { printf '%s✓%s %s\n' "$G" "$R" "$*"; }
warn() { printf '%s!%s %s\n' "$Y" "$R" "$*"; }
fail() { printf '%s✗%s %s\n' "$E" "$R" "$*" >&2; exit 1; }

is_wrapper() { grep -q '^# s3seal:' "$1" 2>/dev/null; }
# On many Linux distributions "mc" is Midnight Commander, not MinIO's client.
is_minio_mc() { "$1" --version 2>/dev/null | grep -q 'RELEASE\.'; }

sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

sum_for() { printf '%s\n' "$CHECKSUMS" | awk -v f="$1" '$2 == f { print $1 }'; }

mc_download_url() {
  local os arch
  case "$(uname -s)" in
    Linux) os=linux ;;
    Darwin) os=darwin ;;
    *) os="$(uname -s | tr '[:upper:]' '[:lower:]')" ;;
  esac
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    aarch64|arm64) arch=arm64 ;;
    *) arch="$(uname -m)" ;;
  esac
  printf 'https://dl.min.io/client/mc/release/%s-%s/mc' "$os" "$arch"
}

printf '\n%ss3seal installer%s\n\n' "$B" "$R"
info "s3seal keeps AWS and mc keys encrypted with GPG instead of plaintext files."
info ""

command -v gpg >/dev/null 2>&1 || fail "gpg is required"

# --- stage the files, from this checkout or from GitHub ----------------------
stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT
mkdir -p "$stage/lib"

script_dir=""
if [[ -n "${BASH_SOURCE[0]:-}" && -f "${BASH_SOURCE[0]}" ]]; then
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

if [[ -n "$script_dir" && -f "$script_dir/mc" && -f "$script_dir/lib/common.sh" ]]; then
  for f in $FILES; do cp "$script_dir/$f" "$stage/$f"; done
  ok "using s3seal from this checkout"
else
  command -v curl >/dev/null 2>&1 || fail "curl is required to download s3seal"
  verify=0
  [[ "$REPO" == "$DEFAULT_REPO" && "$REF" == "$DEFAULT_REF" ]] && verify=1
  for f in $FILES; do
    curl -fsSL "$RAW_URL/$f" -o "$stage/$f" || fail "download failed: $RAW_URL/$f"
    if (( verify )); then
      expected="$(sum_for "$f")"
      actual="$(sha256 "$stage/$f")"
      [[ -n "$expected" && "$actual" == "$expected" ]] \
        || fail "checksum mismatch for $f (expected ${expected:-none}, got $actual). Refusing to install."
    fi
  done
  if (( verify )); then
    ok "downloaded and verified s3seal from $REPO@$REF"
  else
    warn "downloaded s3seal from $REPO@$REF; not verified (only the default ref has checksums)"
  fi
fi

for f in $ENTRIES; do
  head -n1 "$stage/$f" | grep -q '^#!' || fail "$f does not look like a script"
  grep -q '^# s3seal:' "$stage/$f" || fail "$f is not an s3seal file"
done
for f in $FILES; do
  bash -n "$stage/$f" || fail "$f failed a syntax check; refusing to install"
done

# --- the real mc must be off PATH, because the mc wrapper takes its name ----
found_mc=""
while IFS= read -r candidate; do
  [[ -n "$candidate" ]] || continue
  is_wrapper "$candidate" && continue
  if ! is_minio_mc "$candidate"; then
    warn "$candidate is not the MinIO client (Midnight Commander?); the mc wrapper will shadow it on PATH."
    continue
  fi
  found_mc="$candidate"
  break
done < <(type -a -p mc 2>/dev/null || true)

if [[ -n "$found_mc" ]]; then
  fail "the real mc binary is still on your PATH: $found_mc
Move it out of PATH so the wrapper can take over the \"mc\" name:
    mkdir -p $LIBEXEC_DIR && mv $found_mc $LIBEXEC_DIR/mc
Then re-run this installer."
fi

real_mc=""
for candidate in "${MC_BIN:-}" "$LIBEXEC_DIR/mc" "/usr/local/libexec/mc" "/opt/minio/mc"; do
  [[ -n "$candidate" && -x "$candidate" ]] || continue
  is_wrapper "$candidate" && continue
  is_minio_mc "$candidate" || { warn "ignoring $candidate: not the MinIO client"; continue; }
  real_mc="$candidate"
  break
done

if [[ -z "$real_mc" ]]; then
  fail "could not find the real mc binary.
s3seal does not bundle the MinIO client; it wraps yours.
Put it at $LIBEXEC_DIR/mc, or set MC_BIN, then re-run. To download it:
    mkdir -p $LIBEXEC_DIR && curl -fsSL $(mc_download_url) -o $LIBEXEC_DIR/mc && chmod +x $LIBEXEC_DIR/mc"
fi
ok "found the real MinIO client at $real_mc"

# --- compare with what is already installed ----------------------------------
version_of() { sed -n 's/^VERSION="\(.*\)"$/\1/p' "$1" 2>/dev/null | head -n1; }

installed_version=""
[[ -f "$SHARE_DIR/s3seal" ]] && installed_version="$(version_of "$SHARE_DIR/s3seal")"
new_version="$(version_of "$stage/s3seal")"

changed=()
for f in $FILES; do
  cmp -s "$stage/$f" "$SHARE_DIR/$f" || changed+=("$f")
done

if [[ -z "$installed_version" ]]; then
  state=fresh
elif (( ${#changed[@]} == 0 )); then
  state=same
elif [[ "$installed_version" == "$new_version" ]]; then
  state=refresh
else
  state=upgrade
fi

case "$state" in
  fresh)   info "Installing s3seal $new_version." ;;
  same)    ok "s3seal $new_version is already installed and up to date. Nothing to copy." ;;
  refresh) info "s3seal $new_version is already installed. Refreshing ${#changed[@]} changed file(s)." ;;
  upgrade) info "Upgrading s3seal $installed_version -> $new_version." ;;
esac

# --- install ----------------------------------------------------------------
mkdir -p "$SHARE_DIR/lib" "$INSTALL_DIR"
if [[ "$state" != same ]]; then
  for f in "${changed[@]}"; do
    case "$f" in
      lib/*) mode=0644 ;;
      *) mode=0755 ;;
    esac
    # Write beside the target and rename over it: a running s3seal keeps its old
    # file, so an upgrade started from s3seal itself cannot corrupt the process.
    install -m "$mode" "$stage/$f" "$SHARE_DIR/$f.new"
    mv -f "$SHARE_DIR/$f.new" "$SHARE_DIR/$f"
  done
  ok "installed s3seal $new_version into $SHARE_DIR"
fi
printf '%s %s\n' "$REPO" "$REF" > "$SHARE_DIR/source"

# Replaces a symlink or an older regular-file wrapper; refuses anything else.
link_entry() {
  local target="$INSTALL_DIR/$1"
  if [[ -L "$target" && "$(readlink "$target")" == "$SHARE_DIR/$1" ]]; then
    return 0
  fi
  if [[ -e "$target" || -L "$target" ]]; then
    if [[ -L "$target" ]] || is_wrapper "$target"; then
      rm -f "$target"
    else
      fail "$target exists and is not s3seal; move it aside and re-run"
    fi
  fi
  ln -s "$SHARE_DIR/$1" "$target"
  ok "linked $1 into $INSTALL_DIR"
}
link_entry mc
link_entry s3seal

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
printf '%s\n' "$real_mc" > "$CONFIG_DIR/mc-path"
ok "recorded the real mc path in $CONFIG_DIR/mc-path"

case ":$PATH:" in
  *":$INSTALL_DIR:"*) ;;
  *)
    warn "$INSTALL_DIR is not on your PATH. Add this to your shell rc file and start a new shell:"
    info "    export PATH=\$PATH:$INSTALL_DIR"
    ;;
esac

if [[ ! -s "$CONFIG_DIR/recipient" && -z "${S3SEAL_GPG_RECIPIENT:-}" ]]; then
  warn "no GPG recipient configured yet:"
  info "    echo 'you@example.com' > $CONFIG_DIR/recipient   (or gpg --full-generate-key first)"
fi

if [[ "$state" == fresh ]]; then
  info ""
  info "Next steps:"
  info "  1. mc alias set prod https://minio.example.com      # stored encrypted"
  info "  2. s3seal enable aws                                 # seal existing AWS profiles, then use aws as before"
  info "  3. s3seal status                                     # shows what is sealed"
else
  info ""
  info "Run 's3seal status' to see what is sealed. Upgrade later with 's3seal upgrade'."
fi
